"""altera usuarios para perfil de permissao

Revision ID: 4beb2ff00b47
Revises: dfe6af28ea1c
Create Date: 2026-05-23 15:35:32.534205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4beb2ff00b47'
down_revision = 'dfe6af28ea1c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('perfil', sa.String(length=20), nullable=True)
        )

    op.execute("""
        UPDATE usuarios
        SET perfil = CASE
            WHEN nivel_permissao = 1 THEN 'MILITAR'
            WHEN nivel_permissao = 2 THEN 'HOMOLOGADOR'
            WHEN nivel_permissao = 3 THEN 'ADMIN'
            ELSE 'MILITAR'
        END
    """)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('perfil', nullable=False)
        batch_op.drop_column('nivel_permissao')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel_permissao', sa.INTEGER(), nullable=False))
        batch_op.drop_column('perfil')

    # ### end Alembic commands ###
