"""cria auditoria

Revision ID: b7a1f8bea9eb
Revises: e98be67e2894
Create Date: 2026-05-29 08:15:07.584133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a1f8bea9eb'
down_revision = 'e98be67e2894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('entidade', sa.String(length=100), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    op.drop_table('auditoria')
    # ### end Alembic commands ###
