"""estrutura inicial do sistema

Revision ID: cde5df87e24f
Revises: 
Create Date: 2026-05-22 09:04:50.148007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde5df87e24f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posto_graduacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_de_fato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('sinal', sa.String(length=10), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('militares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_guerra', sa.String(length=120), nullable=False),
    sa.Column('identidade_militar', sa.String(length=30), nullable=False),
    sa.Column('id_posto_graduacao', sa.Integer(), nullable=False),
    sa.Column('data_de_praca', sa.Date(), nullable=False),
    sa.Column('id_secao', sa.Integer(), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_posto_graduacao'], ['posto_graduacao.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_secao'], ['secoes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identidade_militar')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('nivel_permissao', sa.String(length=20), nullable=False),
    sa.Column('militar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['militar_id'], ['militares.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fatos_observados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('militar_id', sa.Integer(), nullable=False),
    sa.Column('cadastrador_id', sa.Integer(), nullable=False),
    sa.Column('homologador_id', sa.Integer(), nullable=True),
    sa.Column('tipo_de_fato_id', sa.Integer(), nullable=False),
    sa.Column('sinal', sa.String(length=10), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('justificativa_recusa', sa.Text(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('data_homologacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cadastrador_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['homologador_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['militar_id'], ['militares.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_de_fato_id'], ['tipo_de_fato.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidencias_fo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fato_id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fato_id'], ['fatos_observados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_edicao_fo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fato_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('descricao_antiga', sa.Text(), nullable=True),
    sa.Column('descricao_nova', sa.Text(), nullable=True),
    sa.Column('data_edicao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fato_id'], ['fatos_observados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_edicao_fo')
    op.drop_table('evidencias_fo')
    op.drop_table('fatos_observados')
    op.drop_table('usuarios')
    op.drop_table('militares')
    op.drop_table('tipo_de_fato')
    op.drop_table('secoes')
    op.drop_table('posto_graduacao')
    # ### end Alembic commands ###
