"""adiciona texto boletim ao tipo de fo

Revision ID: df02622a6eef
Revises: f83ffbfed540
Create Date: 2026-05-23 17:13:54.962792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df02622a6eef'
down_revision = 'f83ffbfed540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_de_fato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto_boletim', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_de_fato', schema=None) as batch_op:
        batch_op.drop_column('texto_boletim')

    # ### end Alembic commands ###
