"""adiciona status ativo ao militar

Revision ID: e98be67e2894
Revises: df02622a6eef
Create Date: 2026-05-26 12:25:48.420316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98be67e2894'
down_revision = 'df02622a6eef'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('militares', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('ativo', sa.Boolean(), nullable=True)
        )

    op.execute("UPDATE militares SET ativo = 1")

    with op.batch_alter_table('militares', schema=None) as batch_op:
        batch_op.alter_column('ativo', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('militares', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
