"""remove evidencias

Revision ID: f83ffbfed540
Revises: 4beb2ff00b47
Create Date: 2026-05-23 16:34:18.334756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83ffbfed540'
down_revision = '4beb2ff00b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidencias_fo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidencias_fo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fato_id', sa.INTEGER(), nullable=False),
    sa.Column('nome_original', sa.VARCHAR(length=255), nullable=False),
    sa.Column('nome_arquivo', sa.VARCHAR(length=255), nullable=False),
    sa.Column('caminho', sa.VARCHAR(length=500), nullable=False),
    sa.Column('tipo_mime', sa.VARCHAR(length=100), nullable=False),
    sa.Column('data_upload', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['fato_id'], ['fatos_observados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
